Repository Skrwbrgle/Mini-TixPro, pull requests merged in 2023-10, with the labels that each got.

#28 Development
  client/src/App.css
  client/src/App.js
  client/src/components/CardEvent.js
  client/src/components/Footer.js
  client/src/components/MainContent.js
  client/src/components/NavigateBar.js
  client/src/components/ProfilePage.js
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
Labels: enhancement, help wanted

#29 BugFix
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/NavigateBar.js
  client/src/components/ProfilePage.js
Labels: documentation, help wanted

#30 Development and Bugfix
  client/src/components/NavigateBar.js
  client/src/components/ProfilePage.js
Labels: documentation, help wanted

#31 Bug
  client/src/App.css
  client/src/components/MainContent.js
  client/src/components/NavigateBar.js
  client/src/components/Seat.js
  client/src/components/index.js
  client/src/views/DetailPage.js
  client/src/views/HomePage.js
  client/src/views/ProfilePage.js
  client/src/views/index.js
Labels: bug

#32 BugFix
  client/src/App.css
  client/src/views/DetailPage.js
Labels: documentation

#33 New Feature
  client/package.json
  client/src/components/Footer.js
  client/src/components/FooterStyles.js
Labels: documentation, enhancement
